ALL_SINGLE_ARM_ROBOTS = ["Panda", "Sawyer", "IIWA", "UR5e", "Jaco", "Kinova3"]

DOF_MAP = {
    "Panda": 7,
    "Sawyer": 7,
    "IIWA": 7,
    "UR5e": 6,
    "Jaco": 6,
    "Kinova3": 7
}

OBJECT = ["coffee_machine",
          "mug",
          "drawer",
          "coffee_pod",
          "hammer",
          "button",
          "pot",
          "bread",
          "stove",
          "serving_region",
          "object",
          "square_nut",
          "square_peg",
          "round_nut",
          "round_peg",
          "milk",
          "cereal",
          "can",
          "cubeA",
          "cubeB",
          "cubeC",
          "needle",
          "tripod",
          "base",
          "piece_1",
          "piece_2",]

TASKS = ["Coffee", "CoffeePreparation", "HammerCleanup", "Kitchen",
         "MugCleanup", "Square", "PickPlace", "Stack", "StackThree", "Threading"]

TASKS_MAP = {"Coffee": ["Coffee_D0", "Coffee_D1", "Coffee_D2"],
            "CoffeePreparation": ["CoffeePreparation_D0", "CoffeePreparation_D1"],
            "HammerCleanup": ["HammerCleanup_D0", "HammerCleanup_D1"],
            "Kitchen": ["Kitchen_D0", "Kitchen_D1"],
            "MugCleanup": ["MugCleanup_D0", "MugCleanup_D1"],
            "Square": ["Square_D0", "Square_D1", "Square_D2"],
            "PickPlace": ["PickPlace_D0"],
            "Stack": ["Stack_D0", "Stack_D1"],
            "StackThree": ["StackThree_D0", "StackThree_D1"],
            "Threading": ["Threading_D0", "Threading_D1", "Threading_D2"]}

TASK_SPEC_MAP = {"Coffee": "robotDB/taskspecs/coffee.json",
                 "CoffeePreparation": "robotDB/taskspecs/coffee_preparation.json",
                 "HammerCleanup": "robotDB/taskspecs/hammer_cleanup.json",
                 "Kitchen": "robotDB/taskspecs/kitchen.json",
                 "MugCleanup": "robotDB/taskspecs/mug_cleanup.json",
                 "Square": "robotDB/taskspecs/square.json",
                 "PickPlace": "robotDB/taskspecs/pick_place.json",
                 "Stack": "robotDB/taskspecs/stack.json",
                 "StackThree": "robotDB/taskspecs/stack_three.json",
                 "Threading": "robotDB/taskspecs/threading.json"}

TASK_DESCRIPTION_MAP = {"Coffee": "Pick a coffee pod, insert into coffee machine, and close the machine hinge.",
                        "CoffeePreparation": "Load mug onto machine, open machine, retrieve coffee pod from drawer and insert into machine.",
                        "HammerCleanup": "Open drawer, pick hammer, and place into drawer, and close drawer.",
                        "Kitchen": "Switch stove on, place pot onto stove, place bread into pot, place pot in front of serving region and push it there, and turn off the stove.",
                        "MugCleanup": "Open drawer, pick mug, and place into drawer, and close drawer.",
                        "Square": "Pick a square nut and place on a peg.",
                        "PickPlace": "Place four objects into four different bins.",
                        "Stack": "Stack a red block on a green one.",
                        "StackThree": "Same as Stack, but additionally stack a blue block on the red one.",
                        "Threading": "Pick a needle and thread through a hole on a tripod."}

TASK_TYPE_MAP = {"Coffee": "contact_rich",
                 "CoffeePreparation": "long_horizon",
                 "HammerCleanup": "contact_rich",
                 "Kitchen": "long_horizon",
                 "MugCleanup": "contact_rich",
                 "Square": "contact_rich",
                 "PickPlace": "long_horizon",
                 "Stack": "dexterous_manipulation",
                 "StackThree": "dexterous_manipulation",
                 "Threading": "contact_rich"}

TASK_DIFFICULTY_MAP = {"Coffee": "medium",
                        "CoffeePreparation": "hard",
                        "HammerCleanup": "medium",
                        "Kitchen": "hard",
                        "MugCleanup": "medium",
                        "Square": "easy",
                        "PickPlace": "hard",
                        "Stack": "easy",
                        "StackThree": "medium",
                        "Threading": "medium"}

TASK_TO_SUBTASKS = {"Coffee": ["grasp_pod", "insert_into_machine"],
                    "CoffeePreparation": ["mug_grasp", "mug_place", "drawer_open", "pod_grasp","prepare_coffee"],
                    "HammerCleanup": ["open_drawer", "grasp_hammer", "put_into_drawer"],
                    "Kitchen": ["stove_on", "grasp_pot", "place_pot_on_stove", "grasp_bread", "place_bread_in_pot", "place_to_serve", "stove_off"],
                    "MugCleanup": ["open_drawer", "grasp_mug", "put_into_drawer"],
                    "Square": ["pick_square_nut", "place_square_nut_on_square_peg"],
                    "PickPlace": ["grasp_milk", "place_milk", "grasp_cereal", "place_cereal", "grasp_bread", "place_bread", "grasp_can", "place_can"],
                    "Stack": ["grasp_cubeA", "place_cubeA_on_cubeB"],
                    "StackThree": ["grasp_cubeA", "place_cubeA_on_cubeB", "grasp_cubeC", "place_cubeC_on_cubeB"],
                    "Threading": ["grasp_needel", "thread_needle_through_tripod"]}

SUBTASK_TO_RELATIVE_OBJECTS = {
    "grasp_pod": ["coffee_pod"],
    "insert_into_machine": ["coffee_machine"],
    "mug_grasp": ["mug"],
    "mug_place": ["coffee_machine"],
    "drawer_open": ["drawer"],
    "pod_grasp": ["coffee_pod"],
    "prepare_coffee": ["coffee_machine"],
    "open_drawer": ["drawer"],
    "grasp_hammer": ["hammer"],
    "put_into_drawer": ["drawer"],
    "stove_on": ["stove"],
    "grasp_pot": ["pot"],
    "place_pot_on_stove": ["stove"],
    "grasp_bread": ["bread"],
    "place_bread_in_pot": ["pot"],
    "place_to_serve": ["serving_region"],
    "stove_off": ["button"],
    "grasp_mug": ["mug"],
    "grasp_cubeA": ["cubeA"],
    "place_cubeA_on_cubeB": ["cubeB"],
    "grasp_cubeC": ["cubeC"],
    "place_cubeC_on_cubeB": ["cubeA"],
    "grasp_needel": ["needle"],
    "thread_needle_through_tripod": ["tripod"] ,
    "pick_square_nut": ["square_nut"],
    "place_square_nut_on_square_peg": ["square_peg"], 
    "grasp_milk": ["milk"],
    "place_milk": ["object"],
    "grasp_cereal": ["cereal"],
    "place_cereal": ["object"],
    "grasp_bread": ["bread"],
    "place_bread": ["object"],
    "grasp_can": ["can"],
    "place_can": ["object"]  
}

SUBTASK_DESCRIPTION_MAP = {
    "grasp_pod": "Grasp a coffee pod.",
    "insert_into_machine": "Insert the coffee pod into the coffee machine.",
    "mug_grasp": "Grasp a mug.",
    "mug_place": "Place the mug onto the coffee machine.",
    "drawer_open": "Open the drawer.",
    "pod_grasp": "Grasp a coffee pod.",
    "prepare_coffee": "Prepare the coffee.",
    "open_drawer": "Open the drawer.",
    "grasp_hammer": "Grasp a hammer.",
    "put_into_drawer": "Put the hammer into the drawer.",
    "stove_on": "Switch on the stove.",
    "grasp_pot": "Grasp a pot.",
    "place_pot_on_stove": "Place the pot onto the stove.",
    "grasp_bread": "Grasp a bread.",
    "place_bread_in_pot": "Place the bread into the pot.",
    "place_to_serve": "Place the pot in front of the serving region.",
    "stove_off": "Turn off the stove.",
    "grasp_mug": "Grasp a mug.",
    "grasp_cubeA": "Grasp a cubeA.",
    "place_cubeA_on_cubeB": "Place the cubeA on top of cubeB.",
    "grasp_cubeC": "Grasp a cubeC.",
    "place_cubeC_on_cubeB": "Place the cubeC on top of cubeB.",
    "grasp_needel": "Grasp a needle.",
    "thread_needle_through_tripod": "Thread the needle through the hole on the tripod.",
    "pick_square_nut": "Pick a square nut.",
    "place_square_nut_on_square_peg": "Place the square nut on the square peg.",
    "grasp_milk": "Grasp a milk.",
    "place_milk": "Place the milk into a bin.",
    "grasp_cereal": "Grasp a cereal.",
    "place_cereal": "Place the cereal into a bin.",
    "grasp_bread": "Grasp a bread.",
    "place_bread": "Place the bread into a bin.",
    "grasp_can": "Grasp a can.",
    "place_can": "Place the can into a bin."
}